/crazyflie_server:
  dds:
    domain_id: 1
    rmw_implementation: rmw_fastrtps_cpp
  qos:
    avoid_ros_namespace_conventions: false
    deadline: 0
    depth: 10
    durability: volatile
    history: keep_last
    lifespan: 0
    liveliness: system_default
    liveliness_lease_duration: 0
    reliability: reliable
  ros__parameters:
    backend: cflib
    firmware_params:
      query_all_values_on_connect: false
    sim:
      backend: np
      controller: mellinger
      max_dt: 0
      visualizations:
        blender:
          cf_cameras:
            cf231:
              calibration:
                rvec:
                - 1.2092
                - -1.2092
                - 1.2092
                tvec:
                - 0
                - 0
                - 0
            cf5:
              calibration:
                rvec:
                - 0.61394313
                - -0.61394313
                - 1.48218982
                tvec:
                - 0
                - 0
                - 0
          cycle_bg: false
          enabled: false
          fps: 1
        pdf:
          enabled: false
          output_file: result.pdf
        record_states:
          enabled: false
          file_formats:
          - csv
          - np
          logging_time: 0.2
          output_dir: state_info
        rviz:
          enabled: true
    warnings:
      communication:
        max_unicast_latency: 10.0
        min_broadcast_receive_rate: 0.9
        min_unicast_ack_rate: 0.9
        min_unicast_receive_rate: 0.9
        publish_stats: false
      frequency: 1.0
      motion_capture:
        warning_if_rate_outside:
        - 80.0
        - 120.0
