name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Checkout NokovSwarm
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
      
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.8'
        activate-environment: nokovswarm
        environment-file: nokov_swarm/nokov_swarm/environment.yaml
        
    - name: Test with pytest
      run: |
        cd nokov_swarm/nokov_swarm/test
        ./run_all_test.sh
        
    - name: Package with Script
      run: |
        cd nokov_swarm/nokov_swarm/build_scripts
        ./build_linux.sh
