name: NokovSwarm

on:
  push:
    branches:
      - week5

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install ROS 2
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-desktop
          
      - name: Update Submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
          path: nokov_swarm
          submodules: true

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libegl1 libxcb-xinerama0
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.8'
          activate-environment: nokovswarm
          environment-file: nokov_swarm/nokov_swarm/nokov_swarm/environment.yaml
          auto-activate-base: false
          
      - name: Initialize and activate environment
        run: |
          conda init bash
          source ~/.bashrc
          conda activate nokovswarm
          conda env list  # 验证环境
          
      - name: Run tests
        run: |
          conda init bash
          source ~/.bashrc
          conda activate nokovswarm
          cd nokov_swarm/nokov_swarm/test
          ./run_all_test.sh
  
      - name: Package
        run: |
          conda init bash
          source ~/.bashrc
          conda activate nokovswarm          
          cd nokov_swarm/nokov_swarm/nokov_swarm/build_scripts
          ./build_linux.sh
          cd ../dist
          ./NokovSwarm
      
