name: NokovSwarm

on:
  push:
    branches:
      - week5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Update Submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
          path: nokov_swarm
          submodules: true
          
      - name: Test Submodules
        run: |
          cd nokov_swarm/nokov_swarm
          tree nokov_swarm
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.8'
          activate-environment: nokovswarm
          environment-file: ${{ github.workspace }}/nokov_swarm/nokov_swarm/nokov_swarm/environment.yaml

      - name: Run tests
        run: |
          conda activate nokovswarm
          cd nokov_swarm/test
          ./run_all_test.sh
  
      - name: Package
        run: |
          conda activate nokovswarm
          cd nokov_swarm/nokov_swarm/build_scripts
          ./build_linux.sh
          cd ../dist
          ./NokovSwarm
      
