name: NokovSwarm

on:
  push:
    branches:
      - week5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Update Submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
          path: nokov_swarm
          submodules: true
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.8'
          activate-environment: nokovswarm
          environment-file: nokov_swarm/nokov_swarm/nokov_swarm/environment.yaml
          auto-activate-base: false
      - name: Initialize and activate environment
        run: |
          conda init bash
          source ~/.bashrc
          conda activate nokovswarm
          conda env list  # 验证环境
          
      - name: Run tests
        run: |
          cd nokov_swarm/nokov_swarm/test
          ./run_all_test.sh
  
      - name: Package
        run: |
          cd nokov_swarm/nokov_swarm/nokov_swarm/build_scripts
          ./build_linux.sh
          cd ../dist
          ./NokovSwarm
      
